apiVersion: apps/v1
kind: Deployment
metadata:
  name: capstone-app-deployment
  labels:
    app: healthcare-app
spec:
  replicas: 3
  selector:
    matchLabels:
      app: healthcare-app
  template:
    metadata:
      labels:
        app: healthcare-app
    spec:
      containers:
      - name: capstone-app-container
        image: azharhashmi/medicure:7.0
        ports:
        - containerPort: 8090
---
apiVersion: v1
kind: Service
metadata:
  name: healthcare-app-service
spec:
  selector:
    app: healthcare-app
  ports:
  - protocol: TCP
    port: 8085
    targetPort: 8090
    type: NodePort
